---
abstract: "Support code for \"Perl on a Stick\""
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perl-Portable
no_index:
  directory:
    - share
    - inc
    - t
requires:
  File::Spec: 0.80
  List::Util: 1.19
  Object::Tiny: 1.04
  Params::Util: 0.31
  YAML::Tiny: 1.29
  perl: 5.8.0
version: 0.02
